FROM alpine

RUN apk add --update nodejs npm

WORKDIR usr/src/app

COPY package.json .

RUN npm install 

# copy  only the source code and not the dependencies folder
COPY app-v2.js . 

ENV PORT 4000

EXPOSE 4000

CMD ["node","app-v2.js"]